
# Schema can be found here:
# https://github.com/WoolworthsCORP/AzureDevOps-Blueprints/blob/1.1.0/templates/pipelines/infrastructure/readme.md

#################################################
# Resources
#################################################
# https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout
resources:
  repositories:
    - repository: blueprints
      type: github
      endpoint: 'Github Service Connection'
      name: WoolworthsCORP/AzureDevOps-Blueprints
      ref: refs/tags/v1.4.31

#################################################
# Triggers
#################################################
pr: none
trigger: none

#################################################
# Parameters
#################################################
parameters:
  - name: appServices
    type: object
    default:
      - applicationServiceID: 'mft-dev-azure'
        approvalGate: true
        approvalEnvName: nonprod_azure # or nonprod_gcp
        changeEnabled: true
        changeNumber: NONE_NEW_ONE_WILL_BE_CREATED
        buildsheetUrl: ''
        virtualMachineJob: true

      - applicationServiceID: 'mft-uat-azure'
        approvalGate: true
        approvalEnvName: nonprod_azure # or nonprod_gcp
        changeEnabled: true
        changeNumber: 'NONE_NEW_ONE_WILL_BE_CREATED'
        buildsheetUrl: ''
        virtualMachineJob: true

      - applicationServiceID: 'mft-prod-azure'
        approvalGate: true
        approvalEnvName: prod_azure # or nonprod_gcp
        changeEnabled: true
        changeNumber: 'NONE_NEW_ONE_WILL_BE_CREATED'
        buildsheetUrl: 'https://docs.google.com/spreadsheets/d/1YKeH7WGZ1B9RoYKP0TUpgmfOQ3_4_7w4OKE71NQ9IWo/edit#gid=1204723306'
        virtualMachineJob: true  

#      - applicationServiceID: '<tla>-prod-<cloud>'
#        dependsOn: '<tla>-uat-<cloud>'
#        approvalGate: true
#        approvalEnvName: prod_azure # or nonprod_gcp
#        changeEnabled: false
#        changeNumber: 'NONE_NEW_ONE_WILL_BE_CREATED'
#        buildsheetUrl: 'https://BUILDSHEETURL'
#        virtualMachineJob: true

#################################################
# Job Definition
#################################################
extends:
  template: templates/stages/tfe/deploy-appsvcs.yml@blueprints
  parameters:
    appServices:  ${{ parameters.appServices }}
    # Uncomment in Sandpit
    # windowsAgentPool: Enterprise
    linuxAgentPool: azd-shared-rhel
