
# Schema can be found here:
# https://github.com/arunsftp/AzureDevOps-Blueprints/blob/1.1.0/templates/pipelines/infrastructure/readme.md

#################################################
# Resources
#################################################
# https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout
resources:
  repositories:
    - repository: blueprints
      type: github
      endpoint: 'github.com_arunsftp' # 'Github Service Connection'
      name: arunsftp/AzureDevOps-Blueprints
      #ref: refs/tags/v1.4.31

#################################################
# Triggers
#################################################
pr: none
trigger: none

#################################################
# Parameters
#################################################
parameters:
  - name: appServices
    type: object
    default:
      - applicationServiceID: 'eks-eBUS-np-green'
        approvalGate: true
        approvalEnvName: nonprod_aws # or nonprod_azure
        changeEnabled: true
        changeNumber: NONE_NEW_ONE_WILL_BE_CREATED
        buildsheetUrl: ''
        virtualMachineJob: true

      - applicationServiceID: 'eks-eBUS-np-blue'
        approvalGate: true
        approvalEnvName: nonprod_aws # or nonprod_azure
        changeEnabled: true
        changeNumber: 'NONE_NEW_ONE_WILL_BE_CREATED'
        buildsheetUrl: ''
        virtualMachineJob: true

      - applicationServiceID: 'eks-eBUS-prod-green'
        dependsOn: 'eks-eBUS-np-green'
        approvalGate: true
        approvalEnvName: prod_aws # or prod_azure
        changeEnabled: true
        changeNumber: 'NONE_NEW_ONE_WILL_BE_CREATED'
        buildsheetUrl: 'https://BUILDSHEETURL'
        virtualMachineJob: true  

      - applicationServiceID: 'eks-eBUS-prod-blue'
        dependsOn: 'eks-eBUS-np-blue'
        approvalGate: true
        approvalEnvName: prod_aws # or prod_azure
        changeEnabled: false
        changeNumber: 'NONE_NEW_ONE_WILL_BE_CREATED'
        buildsheetUrl: 'https://BUILDSHEETURL'
        virtualMachineJob: true

#      - applicationServiceID: '<tla>-prod-<cloud>'
#        dependsOn: '<tla>-uat-<cloud>'
#        approvalGate: true
#        approvalEnvName: prod_azure # or nonprod_gcp
#        changeEnabled: false
#        changeNumber: 'NONE_NEW_ONE_WILL_BE_CREATED'
#        buildsheetUrl: 'https://BUILDSHEETURL'
#        virtualMachineJob: true

#################################################
# Job Definition
#################################################
extends:
  template: templates/stages/tfe/deploy-appsvcs.yml@blueprints
  parameters:
    appServices:  ${{ parameters.appServices }}
    # Uncomment in Sandpit
    # windowsAgentPool: Enterprise
    linuxAgentPool: azd-shared-rhel
